### ISSUE TITLE
mutable reference in the book

### ISSUE THREAD

**Issue by rathingit** [steveklabnik/steveklabnik.com#20]
Sir, correct me if wrong and forgive me for the trouble.
“THE RUST PROGRAMMING LANGUAGE 2nd Edition
Page 133
Mutable references have one big restriction: if you have a mutable
reference to a value, you can have no other references to that value.
This code that attempts to create two mutable references to s will
fail:
src/main.rs
let mut s = String::from("hello");
let r1 = &mut s;
let r2 = &mut s;
println!("{r1}, {r2}");”
My humble observations:
**r1 and r2 are not mutable references.** Because:
**let mut r3  = &mut s;
is a mutable reference.**
In: 
let r1 = &mut s;
let r2 = &mut s;

the error is in the expression &mut s occurring twice. The error is in borrowing. The compiler is exact. If you mutably borrow once a variable, in a given scope, no more borrow is allowed for that variable in that scope.
The word reference is a noun; the word borrow is a verb. The action borrow creates an expression which, if so desired, can be assigned to a reference.

**Comment by steveklabnik** [comment]
I am no longer involved in TRPL. Please file an issue with them. Thank you.
