### ISSUE TITLE
Rewrite your whole site, with an artisanal flourish

### ISSUE THREAD

**Issue by Noah-Kennedy** [steveklabnik/steveklabnik.com#26]
Rewrite it from scratch in your own handrolled code and artistic style. You have three things: TCP packets, delivered via the wonders of the US Postal Service, a set of blog posts meticulously kept preserved over the centuries by a dedicated monastic order, and HTTP responses generated via a literal Rube Goldberg machine which runs to completion on every request and marks specific blotches of ink onto a roll of paper along the way which is digitized at the end of each run via a camera feeding its outputs into a janky OpenCV script. Start from first principles. It won't be that hard, and it'll be fun.

**Comment by steveklabnik** [comment]
ahahaha <3
