### ISSUE TITLE
Broken link in "Rust is more than safety" article?

### ISSUE THREAD

**Issue by nihil2501** [steveklabnik/steveklabnik.com#3]
https://steveklabnik.com/writing/rust-is-more-than-safety

> This is one of the many things that the “Rust” name evokes. Rust was not intended to be a cutting-edge PLT (programming language theory) research language. It was challenging an assumption that I think many of us hold dear: that “progress” means that things always get better. Reality is a bit more complex than that. Yes, we’ve improved on some things, but there are some older things that were actually “better” in some sense, but never quite made it for other reasons. I’ve always phrased this sentiment like this:

> [Untitled](https://steveklabnik.com/writing/Rust%20is%20more%20than%20safety%20dbafb611620445cb9bab3d2ec5828e08/Untitled%20Database%201c7b46da754549118fcf5e3d14a9999a.csv)

**Comment by steveklabnik** [comment]
Thank you!
